config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  post 'users/login' => 'users#login'
  get 'users/login' => 'users#login'
  get 'users/logout' => 'users#logout'
  get 'users/getRoleGrant' => 'users#getRoleGrant'
  post 'users/deleteCollection' => 'users#deleteCollection'
  get 'users/permission/:id' => 'users#permission', as: :permission
  get 'users/user_by_role/:role' => 'users#user_by_role', as: :user_by_role

  get 'members/show' => 'members#show'
  get 'members/profile' => 'members#profile'
  get 'admins/cpn' => 'admins#cpn'

  post 'role_grants/create' => 'role_grants#create'

  get 'user_roles/getRole' => 'user_roles#getRole'

  post 'roles/actionCollection' => 'roles#actionCollection'
  get 'roles/addGrant/:id' => 'roles#addGrant', as: :addGrant

  resources :role_grants

  resources :grants

  resources :users

  resources :user_roles

  resources :roles

  resources :members

  resources :admins

  resources :articles

  resources :emails

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :passWord_confirmation
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many :grants, through: :roles

  validates_confirmation_of :passWord
  validates_uniqueness_of :user_id
  validates_uniqueness_of :userName

  def id_name
    "#{user_id}_#{userName}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout 'member'

  helper_method :testmethod
  #GET root
  #GET users/login

  def login
    session.destroy
    @user = User.where(userName: params[:userName], passWord: params[:passWord], enabled: true)

    if @user.count > 0
      if @user[0].userName == 'admin'
        redirect_to :controller => 'admins', :action => 'index'
        session[:admin] = params[:userName]
      else
        session[:user] = params[:userName]
        redirect_to :controller => 'members', :action => 'index'
      end
      @user2 = User.find_by_userName(params[:userName])
      session[:id] = @user2.id
      getRoleGrant
    end
  end

  def getRoleGrant
    session.delete(:roles_id)
    session.delete(:grant_id)
    session.delete(:grant_name)
    if session[:id]
    @user = User.find(session[:id])
    @userRole = @user.roles.where(:enabled => true)
    if @userRole.count > 0
      @userRole.each do |userRole|
        (session[:roles_id] ||= []) << userRole.id
      end

    end

    if session[:roles_id] && session[:roles_id].size > 0
      session[:roles_id].each do |roleID|
        @userGrantTemp = Role.find(roleID)
        @userGrant = @userGrantTemp.grants
        @userGrant.each do |grant|
          (session[:grant_id] ||= []) << grant.grant_id
          (session[:grant_name] ||= []) << grant.grant_name
        end
      end
      session[:grant_id].uniq!
      session[:grant_name].uniq!
    end
    # @userGrant = @user.grants
    end
  end

  def permission
    session.delete(:permission_id)
    session[:permission_id]=params[:id]
    #new user_role de goi form_for
    @user_role = UserRole.new
    #tim user can cap quyen
    @userTemp = User.find(session[:permission_id])
    @roles = Role.all
    @roles -= @userTemp.roles.where(:enabled => true)
    @roles -= Role.where(:enabled => false)
    #tim user tra ve collection_select
     @user = User.where(:id=>  session[:permission_id])

    #tim ra cac quyen cua user
    @user_roles = UserRole.where(user_id:  session[:permission_id])


    respond_to do |format|
      format.html
      format.js
    end
  end

  #GET /users/logout
  def logout
    session.destroy
    redirect_to :controller => 'users', :action => 'login'
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @allroles = Role.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def user_by_role
    @allroles = Role.all
    @role_id = params[:role]
    # @roletemp = UserRole.find(params[:role])
    @user_id = UserRole.where(role_id: params[:role])
    #cach 1: dung tap hop cong tap hop
    @users = User.where(id: '-1')
    @user_id.each do |user|
      @users +=  User.where(id: user.user_id)
      # cach 2: dung array# (@users ||= []) << User.find(user.user_id)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # @user = User.find(params[:id])
  end

  def list
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @users = User.all
    @allroles = Role.all
    respond_to do |format|
      if @user.save
        format.html
        format.js
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
        @note = true
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @users = User.all
        @allroles = Role.all
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        format.js
        @note= true
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js

      end
    end
  end

  def deleteCollection
    #get all user to show user list
    @users = User.all
    @allroles = Role.all
    @arr = params[:chk_user]
    #delete user selection
    # @arr.each do |user|
    #   @user = User.find(user)
    #   if @user.destroy
    #     @note = true
    #   end
    # end
    #enabled user selection
    @action = params[:commit]
    @val = params[:rdoAction]
    if @action.upcase == 'ACTION'
      @arr.each do |user|
        @user = User.find(user)
        @user.update(enabled: @val)
        @note = 'User was successfully updated!'
      end
    else
      if @action.upcase =='DELETE SELECTION'
        @arr.each do |user|
            @user = User.find(user)
            @user.destroy
        end
        @note = 'User was successfully destroyed'
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    @users = User.all
    @allroles = Role.all
    respond_to do |format|
      format.html
      format.js
      # format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :name, :address, :userName, :passWord,:passWord_confirmation, :enabled)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, remote: true) do |f| %>
  <% if @note %>
    <div id="error_explanation">
      <h2 class="error">prohibited this user from being saved:</h2>

      <ul>
        <li><%= @note %></li>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <div class="field">
        <%= f.label 'User ID' %>
        <%= f.text_field :user_id, :class => 'form-control', required: true %>
      </div>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control', required: true %>
      </div>
      <div class="field">
        <%= f.label :address %>
        <%= f.text_field :address, :class => 'form-control', required: true %>
      </div>
      <div class="field">
        <%= f.label :userName %>
        <%= f.text_field :userName, :class => 'form-control', required: true %>
      </div>
      <div class="field">
        <%= f.label :passWord %>
        <%= f.password_field :passWord, :class => 'form-control', required: true %>
      </div>
      <div class="field">
        <%= f.label :passWord_confirmation %>
        <%= f.password_field :passWord_confirmation, :class => 'form-control', required: true %>
      </div>
      <% if session[:admin] %>
      <div class="field">
        <%= f.label 'enabled', :class => 'checkbox-inline' %>
        <%= f.check_box :enabled, :class => 'checkbox' %>
      </div>
      <% end%>
      <br/>
      <br/>
          <div class="actions">
            <%= f.submit :class => 'btn btn-primary'%>
          </div>
    </div>
<% end %>

app/views/users/_index.html.erb
<form action="/users/deleteCollection" method="post" data-remote = 'true'>
  <h1>Listing users</h1>

  <div class="col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-body">
        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
            Fill user by role  <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <% @allroles.each do |role| %>
                <li><%= link_to role.role_name, user_by_role_path(role.id), remote: true  %></li>
            <% end %>
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          </ul>
        </div>
        <!--Delete selection button-->
        <%= submit_tag 'Delete selection', :class => 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>

    <!--Enable user-->
  <div class="col-lg-5">
    <div class="panel panel-primary">
      <div class="panel-body">
        <label class="checkbox-inline" ><%= radio_button_tag 'rdoAction', true,true %>Enable</label>
        <label class="checkbox-inline" ><%= radio_button_tag 'rdoAction', false %>Disable</label>
        <%= submit_tag 'Action', :class => 'btn btn-primary',data: {confirm: 'Are you sure?'} %>

      </div>
    </div>
  </div>

  <table class="table">
  <thead>
    <tr>
      <th>Select</th>
      <th>User</th>
      <th>Username</th>
      <th>Address</th>
      <th>Enabled</th>
      <th colspan="4" style="text-align: center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><input type="checkbox" name="chk_user[]" value="<%= user.id%>"></td>
        <td><%= user.user_id %></td>
        <td><%= user.userName %></td>
        <td><%= user.address %></td>
        <td><%= user.enabled %></td>
        <td><%= link_to 'Show', user, remote: true %></td>
        <td><%= link_to 'Edit', edit_user_path(user), remote: true %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
        <td><%= link_to 'permiss',permission_path(user.id), remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</form>

app/views/users/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.userName %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.passWord %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @user.enabled %>
</p>

app/views/users/create.js.erb
$('#loadcontent').html('<%= j render 'index' %>')
<% if @note %>
alert('User was successfully created!');
<% end %>

app/views/users/deleteCollection.js.erb
<% if @note %>
alert('<%= @note %>');
<% end %>
$('#loadcontent').html('<%= j render 'index' %>')

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/getRoleGrant.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="list-group">
      <a href="" class="list-group-item active">Role</a>
      <% if @userRole %>
      <% @userRole.each do |roles|%>
          <a href="" class='list-group-item'><%= roles.role_name %></a>
      <% end %>
       <% else  %>
          <a href="" class='list-group-item'>You don't have any Role and Grant</a>
       <% end %>
    </div>

    <% if session[:grant_name] %>
    <div class="list-group">
      <a href="#" class="list-group-item active">Grant</a>
      <% session[:grant_name].each do |grant|%>
          <a href="" class='list-group-item'><%= grant %></a>
      <% end %>
    </div>
     <% end %>

  </div>

  <div class="col-lg-9">
    <div class="panel panel-primary">
      <div class="panel-heading">Content</div>
      <div class="panel-body" id="loadcontent">

      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Address</th>
      <th>Username</th>
      <th>Password</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_id %></td>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.userName %></td>
        <td><%= user.passWord %></td>
        <td><%= user.enabled %></td>
        <td><%= link_to 'Show', user, :id=>'grantlist', :class => 'list-group-item', remote: true %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.js.erb
$('#loadcontent').html('<%= j render 'index' %>')

app/views/users/login.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-3 form-group" id="formlogin">
        <h1>Please sign in</h1>
        <%= form_tag '/users/login' do %>

            <%= label_tag 'Username: ' %><br>
            <%= text_field_tag :userName,nil, :class =>'form-control', placeholder: 'Your userName', required: true %><br>

            <%= label_tag 'Password: ' %><br>
            <%= password_field_tag :passWord,nil, :class =>'form-control', placeholder: 'Your passWord', required: true %><br/>

            <%= link_to 'Register! If you don\'t have account', '/users/new', :class => 'label-info' %><br/><br/>
            <%= submit_tag 'Login', :class => 'btn btn-primary' %>

        <% end %>

        </div>
    </div>
</div>

app/views/users/new.html.erb
<div id="formlogin">

    <div class="row">
      <div class="col-lg-6" >
        <div class="panel panel-primary">
          <div class="panel-heading">Register Information</div>
          <div class="panel-body">
            <%= render 'form' %>
          </div>
        </div>


       </div>
    </div>

<!--<%= link_to 'Back', users_path %>-->
</div>

app/views/users/new.js.erb
$('#loadcontent').html('<%= j render 'new' %>')

app/views/users/permission.js.erb
$('#loadcontent').html('<%= j render 'permission' %>')

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.userName %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.passWord %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @user.enabled %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>