config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  post 'users/login' => 'users#login'
  get 'users/login' => 'users#login'
  get 'users/logout' => 'users#logout'
  get 'users/getRoleGrant' => 'users#getRoleGrant'
  post 'users/deleteCollection' => 'users#deleteCollection'
  get 'users/permission/:id' => 'users#permission', as: :permission
  get 'users/user_by_role/:role' => 'users#user_by_role', as: :user_by_role

  get 'members/show' => 'members#show'
  get 'members/profile' => 'members#profile'
  get 'admins/cpn' => 'admins#cpn'

  post 'role_grants/create' => 'role_grants#create'

  get 'user_roles/getRole' => 'user_roles#getRole'

  post 'roles/actionCollection' => 'roles#actionCollection'
  get 'roles/addGrant/:id' => 'roles#addGrant', as: :addGrant

  resources :role_grants

  resources :grants

  resources :users

  resources :user_roles

  resources :roles

  resources :members

  resources :admins

  resources :articles

  resources :emails

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role

  has_many :grants, through: :roles

end

app/controllers/user_roles_controller.rb
require 'users_controller'
class UserRolesController < ApplicationController
  before_action :set_user_role, only: [:show, :edit, :update, :destroy]
  include UsersHelper
  # GET /user_roles
  # GET /user_roles.json
  def index
    @user_roles = UserRole.all
  end


  def getRole
    @user_roles = UserRole.all
    @user = User.all
    @role = Role.all
    @getRoles = UserRole.where(user_id: session[:id])
    session.delete(:roles)
  end

  # GET /user_roles/1
  # GET /user_roles/1.json
  def show
  end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
    @user = User.all
    @role = Role.all
  end

  # GET /user_roles/1/edit
  def edit
  end

  # POST /user_roles
  # POST /user_roles.json
  def create
    @arr = params[:role_id]
    for i in 0..@arr.size-1
      @user_role = UserRole.new(:user_id => params[:user_role][:user_id], :role_id => @arr[i])

        if @user_role.save

          @user_role = UserRole.new
          #tim user can cap quyen
          @userTemp = User.find(session[:permission_id])
          @roles = Role.all
          @roles -= @userTemp.roles.where(:enabled => true)
          @roles -=Role.where(:enabled => false)
          @user = User.where(:id=> session[:permission_id])

          #tim ra cac quyen cua user
          @user_roles = UserRole.where(user_id:  session[:permission_id])
        end
    end

    respond_to do |format|
      # format.html

      format.js
      # format.json { render :show, status: :created, location: @role_grant }
      # else
      #   format.html {}
      # format.json { render json: @role_grant.errors, status: :unprocessable_entity }
    end

    # @user_role = UserRole.new(user_role_params)
    #
    # respond_to do |format|
    #   if @user_role.save
    #     format.html { redirect_to @user_role, notice: 'User role was successfully created.' }
    #     format.json { render :show, status: :created, location: @user_role }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user_role.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /user_roles/1
  # PATCH/PUT /user_roles/1.json
  def update
    respond_to do |format|
      if @user_role.update(user_role_params)
        format.html { redirect_to @user_role, notice: 'User role was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_role }
      else
        format.html { render :edit }
        format.json { render json: @user_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_roles/1
  # DELETE /user_roles/1.json
  def destroy
    @user_role.destroy
    #tim user can cap quyen
    @userTemp = User.find(session[:permission_id])
    @roles = Role.all
    @roles -= @userTemp.roles.where(:enabled => true)
    @roles -= Role.where(:enabled => false)
    #tim user tra ve collection_select
    @user = User.where(:id=>  session[:permission_id])

    #tim ra cac quyen cua user
    @user_roles = UserRole.where(user_id:  session[:permission_id])

    respond_to do |format|
      format.html
      format.js
      # format.html { redirect_to user_roles_url, notice: 'User role was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_role
      @user_role = UserRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_role_params
      params[:user_role]
    end
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/user_roles/_form.html.erb
<%= form_for(@user_role, remote: true) do |f| %>
  <% if @user_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_role.errors.count, "error") %> prohibited this user_role from being saved:</h2>

      <ul>
      <% @user_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.collection_select(:user_id,@user,:id, :id_name) %></p>

    <% for i in 0..@role.count-1 %>

        <input id="role_grant_grant_id" type="checkbox" value="<%= @role[i].id %>" name="role_id[]">
        <label><%=  @role[i].role_name%></label>
        <br/>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_roles/_getRole.html.erb
<div class="row">
  <div class="col-lg-3" id='loadRG'>
    <div class="list-group">
      <a href="#" class="list-group-item active">Grant</a>

        <% if @getRoles.count > 0

              @getRoles.each do |getRole|%>
                <% if getRole.role.enabled
                     (session[:roles] ||= []) << getRole.role.role_id
                %>
                <%= link_to getRole.role.role_id + ' ' + getRole.role.role_name, '/grants/',:id=>'grantlist', :class => 'list-group-item', remote: true%>
               <%   end
                 end
               else
               %>
              <a class='list-group-item'>You don't have any role</a>
         <% end %>
      <% session[:roles].each do |role| %>
          <p><%= role %></p>
        <% end%>
    </div>
  </div>

  <div class="col-lg-9">
    <div class="panel panel-primary">
      <div class="panel-heading">Content</div>
      <div class="panel-body" id="loadcontent">

      </div>
    </div>
  </div>
</div>

app/views/user_roles/create.js.erb
$('#loadcontent').html('<%= j render 'users/permission' %>')

app/views/user_roles/destroy.js.erb
$('#loadcontent').html('<%= j render 'users/permission' %>')

app/views/user_roles/edit.html.erb
<h1>Editing user_role</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_role %> |
<%= link_to 'Back', user_roles_path %>

app/views/user_roles/getRole.js.erb
$('#contentmember').html('<%= j render 'getRole'%>')

app/views/user_roles/index.html.erb
<h1>Listing user_roles</h1>

<table class="table">

  <tbody>
    <% @user_roles.each do |user_role| %>
      <tr>
        <td><%= user_role.user.name%></td>
        <td><%= user_role.role.role_name%></td>
        <td><%= link_to 'Show', user_role %></td>
        <td><%= link_to 'Edit', edit_user_role_path(user_role) %></td>
        <td><%= link_to 'Destroy', user_role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User role', new_user_role_path %>

app/views/user_roles/new.html.erb
<h1>New user_role</h1>

<%= render 'form' %>

<%= link_to 'Back', user_roles_path %>

app/views/user_roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_role_path(@user_role) %> |
<%= link_to 'Back', user_roles_path %>