config/routes.rb
Rails.application.routes.draw do

  root 'users#login'
  post 'users/login' => 'users#login'
  get 'users/login' => 'users#login'
  get 'users/logout' => 'users#logout'
  get 'users/getRoleGrant' => 'users#getRoleGrant'
  post 'users/deleteCollection' => 'users#deleteCollection'
  get 'users/permission/:id' => 'users#permission', as: :permission
  get 'users/user_by_role/:role' => 'users#user_by_role', as: :user_by_role

  get 'members/show' => 'members#show'
  get 'members/profile' => 'members#profile'
  get 'admins/cpn' => 'admins#cpn'

  post 'role_grants/create' => 'role_grants#create'

  get 'user_roles/getRole' => 'user_roles#getRole'

  post 'roles/actionCollection' => 'roles#actionCollection'
  get 'roles/addGrant/:id' => 'roles#addGrant', as: :addGrant

  resources :role_grants

  resources :grants

  resources :users

  resources :user_roles

  resources :roles

  resources :members

  resources :admins

  resources :articles

  resources :emails

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles

  has_many :role_grants, dependent: :destroy
  has_many :grants, through: :role_grants


  def id_name
    "#{role_id}_#{role_name}"
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def addGrant
    session.delete(:addGrant_id)
    session[:addGrant_id]=params[:id]
    #new role_grant de goi form_for
    @role_grant = RoleGrant.new
    #tim role can cap quyen
    @roleTemp = Role.find(session[:addGrant_id])
    @grants = Grant.all
     @grants -= @roleTemp.grants
    @role = Role.where(id: session[:addGrant_id])

    #tim ra cac grant cua role
    @role_grants = RoleGrant.where(role_id: session[:addGrant_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def actionCollection
    @roles = Role.all
    @arr = params[:chk_role]
    @action = params[:rdoAction]
    if @action=='true' || @action=='false'
      @arr.each do |role_id|
        @role = Role.find(role_id)
        @role.update(enabled: @action)
        @note = 'Role was successfully updated!'
      end
    else
      if @action.upcase =='DELETE'
        @arr.each do |role_id|
          @role = Role.find(role_id)
          @role.destroy
          @note = 'Role was successfully deleted!'
        end
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role_id, :role_name, :enabled)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_addGrant.html.erb
<div class="col-lg-6">
  <div class="panel panel-primary">
    <div class="panel-footer">Permiss for <b><%= @roleTemp.role_name %></b> role</div>
    <div class="panel-body" id="loadcontent">
      <%= form_for(@role_grant, remote: true) do |f|%>
          <% if @role_grant.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@role_grant.errors.count, "error") %> prohibited this role_grant from being saved:</h2>

                <ul>
                  <% @role_grant.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <%= f.collection_select(:role_id,@role,:id, :id_name) %></p>

          <% @grants.each do |grant| %>

              <input id="role_grant_grant_id" type="checkbox" value="<%= grant.id %>" name="grant_id[]">
              <label><%=  grant.grant_name%></label>
              <br/>
          <% end %>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<div class="col-lg-6">
  <div class="panel panel-primary">
    <div class="panel-footer">Authorities of <b><%= @roleTemp.role_name %></b> role</div>
    <div class="panel-body" id="loadcontent">
      <table class="table">
        <tbody>
            <% @role_grants.each do |role_grant| %>
                <tr>
                  <td><%= role_grant.grant.grant_name%></td>
                  <td><%= link_to 'Destroy', role_grant, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
                </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role_id %><br>
    <%= f.text_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :role_name %><br>
    <%= f.text_field :role_name %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/_index.html.erb
<form action="/roles/actionCollection" method="post" data-remote='true'>
  <h1>Listing roles</h1>

  <div class="col-lg-7">
    <div class="panel panel-primary">
      <div class="panel-body">
        <label class="checkbox-inline" ><%= radio_button_tag 'rdoAction', true,true %>Enable</label>
        <label class="checkbox-inline" ><%= radio_button_tag 'rdoAction', false %>Disable</label>
        <label class="checkbox-inline" ><%= radio_button_tag 'rdoAction', 'delete' %>Delete</label>
        <%= submit_tag 'Action', :class => 'btn btn-primary',data: {confirm: 'Are you sure?'} %>

      </div>
    </div>
  </div>

  <table class="table">
    <thead>
    <tr>
      <th>Select</th>
      <th>Role id</th>
      <th>Role name</th>
      <th>Enabled</th>
      <th colspan="4" style="text-align: center">Action</th>
    </tr>
    </thead>

    <tbody>
    <% @roles.each do |role| %>
        <tr>
          <td><input type="checkbox" name="chk_role[]" value="<%= role.id %>"></td>
          <td><%= role.role_id %></td>
          <td><%= role.role_name %></td>
          <td><%= role.enabled %></td>
          <td><%= link_to 'Show', role %></td>
          <td><%= link_to 'Edit', edit_role_path(role) %></td>
          <td><%= link_to 'Destroy', role, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <td><%= link_to 'Add grant',addGrant_path(role.id), remote: true %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

</form>

app/views/roles/_new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/actionCollection.js.erb
<% if @note %>
alert('<%= @note %>');
<% end %>
$('#loadcontent').html('<%= j render 'index' %>')

app/views/roles/addGrant.js.erb
$('#loadcontent').html('<%= j render 'addGrant' %>')

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Role</th>
      <th>Role name</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.role_id %></td>
        <td><%= role.role_name %></td>
        <td><%= role.enabled %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/index.js.erb
$('#loadcontent').html('<%= j render 'index' %>')

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/new.js.erb
$('#loadcontent').html('<%= j render 'new' %>')

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role:</strong>
  <%= @role.role_id %>
</p>

<p>
  <strong>Role name:</strong>
  <%= @role.role_name %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @role.enabled %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>